scout_base_node:
  ros__parameters:
    use_sim_time: false
    port_name: can0
    odom_frame: odom
    base_frame: base_link
    odom_topic: odom
    is_scout_mini: false
    is_omni_wheel: false
    simulated_robot: false
    control_rate: 50
